name = "Mods"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5aaee5c96cb9d53ef48ad0e974c9e72ad27dd9068968797307bcd379c3d2af7a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
